### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by hegyhati** [Teaching-projects/SZE-FordProg-2020-GOLD#1]
Legyen egy readme, ahol egyertelmuen le van irva, mik a kituzott celok, tervezett (Aztan majd elkeszitett) sajat eredmenyek.

**Comment by Digheads** [comment]
Readme-t hozzáadtam, a projekt jelen álláspontom szerint OK. Mi legyen a továbbiakban? Vélemény?

**Comment by hegyhati** [comment]
Majd atolvasom rendesen, csinald nyugodtan, amit eltervetel, aztan ha kesz, akkor szolj, meglesem, ennyi :-)

**Comment by Digheads** [comment]
Úgy érzem elkészültem, amint van egy kis időd csekkold le pls!
